name: rave
description: Flutter support for Flutter Wave's RAVE API. Currently supports Mobile Money payments but will soon have support for debit & credit cards
version: 0.0.5
author: "as1ndu <git@drileba.capital>"
homepage: https://github.com/DrilebaCapital/rave

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+1
  crypto: ^2.0.6
  tripledes: ^2.1.0



