name: rave
description: Flutter support for Flutter Wave's RAVE API.
version: 0.0.1
author: "as1ndu <git@drileba.capital>"
homepage: https://github.com/as1ndu/rave

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+1
  crypto: ^2.0.6
  tripledes: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

